# Generated by Django 5.1 on 2024-09-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Наименование комнаты'),
        ),
    ]
